### PR TITLE
Add dependencies using go dep tool

### PR DESCRIPTION
**Pull request by tvi**

### CODE REVIEW

**Comment by ziutek** [comment]
Please explain why is use go dep necessary for this project.

**Comment by tvi** [comment]
Its not necessary, its mostly nice to have. I am fine if you do not accept this merge.

Go projects are moving from global packages to "vendoring". It means that go dep freezes dependencies at certain commit (Gopkg.lock) and installs them to vendor directory.

It makes the work with go projects more pleasant, build & test repeatable.

**Comment by ziutek** [comment]
Thanks. I think it is not need now.  I'm probably biased, because of my recent experiences with learning Android programming (without Studio, only commandline gradle). But when project grows, it is probably unavoidable.

**Comment by tvi** [comment]
ok

**Pull request closed without merging**
